# Configuração do MongoDB
quarkus.mongodb.connection-string=mongodb://${MONGODB_HOST:localhost}:27017
quarkus.mongodb.database=petshop_query_db

# Jacoco Test Coverage Configuration
quarkus.jacoco.report=true
quarkus.jacoco.minimum-line-coverage=0.5

# Configuração do RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Canal de recebimento de eventos
mp.messaging.incoming.client-created.connector=smallrye-rabbitmq
mp.messaging.incoming.client-created.queue.name=query-client-queue
mp.messaging.incoming.client-created.exchange.name=client-events

mp.messaging.incoming.animal-created.connector=smallrye-rabbitmq
mp.messaging.incoming.animal-created.queue.name=query-animal-queue
mp.messaging.incoming.animal-created.exchange.name=animal-events

mp.messaging.incoming.appointment-scheduled.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-scheduled.queue.name=query-appointment-queue
mp.messaging.incoming.appointment-scheduled.exchange.name=appointment-events

mp.messaging.incoming.appointment-cancelled.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-cancelled.queue.name=query-appointment-cancelled-queue
mp.messaging.incoming.appointment-cancelled.exchange.name=appointment-cancelled-events
