apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: petshop-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: petshop-query-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: query-config
            - secretRef:
                name: query-secret
